title = "Honeymoon Photoblog"
baseURL = 'https://honeymoon.ludwi.gg'
languageCode = 'en-us'
theme = "hugo-blog-awesome"


# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "Honeymoon Photoblog"
  defaultColor = "dark" # set default color mode: dark or light
  description = "A photographic documentation of Kelly and Nick's honeymoon"

[params.author]
  avatar = "https://i.imgur.com/HEUHW0a.jpeg"
  intro = "Honeymoon Photoblog"
  name = "Kelly and Nick"
  description = "A photographic documentation of Kelly and Nick's honeymoon"
